# This is a basic workflow to help you get started with Actions

name: EXADEL_extra_task

on:
  push:
    branches: [ master ]
env: 
  DEPLOY_VER: ${{ github.sha }}
  MONTH: "AUGUST"
  DAY_OF_THE_MONTH: 31
  YEAR: 2001
  FAVORITE_DAY_OF_WEEK: ${{ secrets.FAVORITE_DAY_OF_WEEK }}

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list directories of the repo
        run: ls Task1
      - name: print the content of the `log.txt`
        run: cat ./Task1/log.txt
      - name: print DEPLOY_VER variable
        run: echo "HELLO from $DEPLOY_VER commit"
  second_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print the day of the month 
        run: echo $DAY_OF_THE_MONTH
      - name: print the system date and time
        run: date
      - name: print variables content
        run: echo "DAY - $DAY_OF_THE_MONTH \nMONTH - $MONTH \nYEAR - $YEAR"
      - name: prints favourite day of the week variable
        run: echo "My favorite day of week is $FAVORITE_DAY_OF_WEEK"
      - name: the reason why we get nothing when we print out the FAVORITE_DAY_OF_WEEK variable
        run: echo "the reason why we get nothing when we print out the FAVORITE_DAY_OF_WEEK variable is because, this is secret varibale, which means it is not visible while execution"      
